version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sqlserverexpress
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pa55w0rd!
    ports:
      - "1433:1433"
    extra_hosts:
      - "host.docker.internal:host-gateway"